/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bp2_lab_homework;

import java.io.IOException;
import java.nio.file.DirectoryIteratorException;
import java.nio.file.DirectoryStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import javax.swing.DefaultListModel;

/**
 *
 * @author akifkilic
 */
public class Soru5 extends javax.swing.JFrame {

    /**
     * Creates new form Soru5
     */
    
    DefaultListModel model1,model2,model3;
    
    public Soru5() {
        initComponents();
        
        model1=new DefaultListModel();
        model2=new DefaultListModel();
        model3=new DefaultListModel();
        
    
        lst1.setModel(model1);
        lst2.setModel(model2);
        lst3.setModel(model3);
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtpath = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lst1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lst2 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        lst3 = new javax.swing.JList<>();
        combobx = new javax.swing.JComboBox<>();
        btncontents = new javax.swing.JButton();
        writedirectory = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Dizin İsmi");

        jScrollPane1.setViewportView(lst1);

        jScrollPane2.setViewportView(lst2);

        jScrollPane3.setViewportView(lst3);

        combobx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "abc", "abc1", "delete" }));
        combobx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobxActionPerformed(evt);
            }
        });

        btncontents.setText("Show File Contents");
        btncontents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncontentsActionPerformed(evt);
            }
        });

        writedirectory.setText("Write only directory line by line");
        writedirectory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                writedirectoryActionPerformed(evt);
            }
        });

        jLabel2.setText("Add textfile name in combobox");

        jLabel3.setText("List1");

        jLabel4.setText("List2");

        jLabel5.setText("List3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(1070, 1070, 1070))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(writedirectory))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(btncontents)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1)
                        .addGap(33, 33, 33)
                        .addComponent(txtpath, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(combobx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(187, 187, 187)
                        .addComponent(jLabel3)
                        .addGap(115, 115, 115)
                        .addComponent(jLabel4)
                        .addGap(134, 134, 134)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtpath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btncontents)
                                .addGap(30, 30, 30)
                                .addComponent(writedirectory)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 5, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(combobx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel4)
                        .addComponent(jLabel3)))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void writedirectoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_writedirectoryActionPerformed

//        Path dir = Paths.get("/Users/akifkilic/NetBeansProjects/BP2_Lab_Homework/Test");
       
//        String path=txtpath.getText().toString();
         
        Path dir=Paths.get(txtpath.getText()); // 
       
        try (DirectoryStream<Path> stream = Files.newDirectoryStream(dir,"*.{.pdf},{.jpeg},{.txt}")) {
            // yukarda formatımızı belirttik jpeg, pdf veya .txt dosyası ise yazdıracak
            for (Path file : stream) {
                  
                model2.addElement(file.getFileName());
              
    
        // compareto bize iki pathin kıyasını yapıyor eşit veya değil
        // int value=path1.compareTo(path2) / -1,0 veya 1 döncek
        // bunla nasıl sıralama yapacağımızı anlamadım
        
            }
        } catch (IOException | DirectoryIteratorException x) {

        }
        
        
        
        
        
        
    }//GEN-LAST:event_writedirectoryActionPerformed

    private void btncontentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncontentsActionPerformed
        
//    Path dir = Paths.get("/Users/akifkilic/NetBeansProjects/BP2_Lab_Homework/Test");
       
        String path=txtpath.getText().toString();
         
        Path dir=Paths.get(path); // neden çalışmadığını bulamadım direk stringi patha çevirmiyor mu böyle :(
        model1.addElement(dir);
        
       
    try (DirectoryStream<Path> stream = Files.newDirectoryStream(dir)) {
            for (Path file : stream) {

                String s=file.getFileName().toString();
                model1.addElement(s);

            }
        } catch (IOException | DirectoryIteratorException x) {
            System.err.println(x);
        }
         
         
        
        
        
    }//GEN-LAST:event_btncontentsActionPerformed

    private void combobxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobxActionPerformed
//             int selected=combobx.getSelectedIndex();
      Path dir=Paths.get(combobx.getSelectedItem().toString());
        if(combobx.getSelectedIndex()==0) {
      
            try (DirectoryStream<Path> stream = Files.newDirectoryStream(dir)) {
            for (Path file : stream) {

                String s=file.getFileName().toString();
                model3.addElement(s);

            }
        } catch (IOException | DirectoryIteratorException x) {
            System.err.println(x);
        }
           
       }
       if(combobx.getSelectedIndex()==1) {
              try (DirectoryStream<Path> stream = Files.newDirectoryStream(dir)) {
            for (Path file : stream) {

                String s=file.getFileName().toString();
                model3.addElement(s);

            }
        } catch (IOException | DirectoryIteratorException x) {
            System.err.println(x);
        }
       }
       if(combobx.getSelectedIndex()==2) {
              try (DirectoryStream<Path> stream = Files.newDirectoryStream(dir)) {
            for (Path file : stream) {

                String s=file.getFileName().toString();
                model3.addElement(s);

            }
        } catch (IOException | DirectoryIteratorException x) {
            System.err.println(x);
        }
       }
        
    }//GEN-LAST:event_combobxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Soru5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Soru5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Soru5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Soru5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Soru5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncontents;
    private javax.swing.JComboBox<String> combobx;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> lst1;
    private javax.swing.JList<String> lst2;
    private javax.swing.JList<String> lst3;
    private javax.swing.JTextField txtpath;
    private javax.swing.JButton writedirectory;
    // End of variables declaration//GEN-END:variables
}
